---
- name: install apt packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - fail2ban
    - ufw

- name: ensure fail2ban is running
  sudo: yes
  action: service name=fail2ban state=restarted enabled=yes

- name: forbid SSH root login
  sudo: yes
  lineinfile: destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify:
    - restart ssh

- name: reset firewall
  sudo: yes
  action: shell ufw --force reset

- name: allow firewall authorized ports
  sudo: yes
  action: shell ufw allow {{ item }}
  with_items:
    - "22"
    - "80"
    - "5601"
# should be handled by firewall.yml

- name: enable firewall
  sudo: yes
  action: shell ufw --force enable

- name: show firewall status
  sudo: yes
  action: shell ufw status

- name: add elk user
  user: name=elk groups=sudo,admin
